# Generated by Django 4.2.5 on 2023-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
